#!/bin/bash

# Automatically install a few dependencies if they aren't already installed
if command -v pacman &> /dev/null; then
  echo "Installing packages..."
  sudo pacman -S --noconfirm exa stow ripgrep python-pywal tmux vim alacritty
fi

# Get Vundle so plugins can be easily managed
if [ ! -d "$HOME/.vim/bundle/Vundle.vim" ]; then
  git clone https://github.com/VundleVim/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi

# Install plugins from .vimrc
vim -c ":PluginInstall" -c ":q" -c ":q"

# Install oh-my-zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# Stow configs
stow vim
stow tmux
stow xmodmap
stow awesome

# Manually stow zsh stuff since stow doesn't own .oh-my-zsh
ln -f zsh/.zshrc $HOME/.zshrc
ln -f zsh/.oh-my-zsh/themes/pygmalion.zsh-theme $HOME/.oh-my-zsh/themes/pygmalion.zsh-theme
